In [2]:
import numpy as np
import pandas as pd 

In [3]:
dataset = pd.read_csv("../datasets/50_Startups.csv")

In [4]:
dataset

R&D Spend  Administration  Marketing Spend       State     Profit
0   165349.20       136897.80        471784.10    New York  192261.83
1   162597.70       151377.59        443898.53  California  191792.06
2   153441.51       101145.55        407934.54     Florida  191050.39
3   144372.41       118671.85        383199.62    New York  182901.99
4   142107.34        91391.77        366168.42     Florida  166187.94
5   131876.90        99814.71        362861.36    New York  156991.12
6   134615.46       147198.87        127716.82  California  156122.51
7   130298.13       145530.06        323876.68     Florida  155752.60
8   120542.52       148718.95        311613.29    New York  152211.77
9   123334.88       108679.17        304981.62  California  149759.96
10  101913.08       110594.11        229160.95     Florida  146121.95
11  100671.96        91790.61        249744.55  California  144259.40
12   93863.75       127320.38        249839.44     Florida  141585.52
13   91992.39       135495.07        252664.93  California  134307.35
14  119943.24       156547.42        256512.92     Florida  132602.65
15  114523.61       122616.84        261776.23    New York  129917.04
16   78013.11       121597.55        264346.06  California  126992.93
17   94657.16       145077.58        282574.31    New York  125370.37
18   91749.16       114175.79        294919.57     Florida  124266.90
19   86419.70       153514.11             0.00    New York  122776.86
20   76253.86       113867.30        298664.47  California  118474.03
21   78389.47       153773.43        299737.29    New York  111313.02
22   73994.56       122782.75        303319.26     Florida  110352.25
23   67532.53       105751.03        304768.73     Florida  108733.99
24   77044.01        99281.34        140574.81    New York  108552.04
25   64664.71       139553.16        137962.62  California  107404.34
26   75328.87       144135.98        134050.07     Florida  105733.54
27   72107.60       127864.55        353183.81    New York  105008.31
28   66051.52       182645.56        118148.20     Florida  103282.38
29   65605.48       153032.06        107138.38    New York  101004.64
30   61994.48       115641.28         91131.24     Florida   99937.59
31   61136.38       152701.92         88218.23    New York   97483.56
32   63408.86       129219.61         46085.25  California   97427.84
33   55493.95       103057.49        214634.81     Florida   96778.92
34   46426.07       157693.92        210797.67  California   96712.80
35   46014.02        85047.44        205517.64    New York   96479.51
36   28663.76       127056.21        201126.82     Florida   90708.19
37   44069.95        51283.14        197029.42  California   89949.14
38   20229.59        65947.93        185265.10    New York   81229.06
39   38558.51        82982.09        174999.30  California   81005.76
40   28754.33       118546.05        172795.67  California   78239.91
41   27892.92        84710.77        164470.71     Florida   77798.83
42   23640.93        96189.63        148001.11  California   71498.49
43   15505.73       127382.30         35534.17    New York   69758.98
44   22177.74       154806.14         28334.72  California   65200.33
45    1000.23       124153.04          1903.93    New York   64926.08
46    1315.46       115816.21        297114.46     Florida   49490.75
47       0.00       135426.92             0.00  California   42559.73
48     542.05        51743.15             0.00    New York   35673.41
49       0.00       116983.80         45173.06  California   14681.40

In [5]:
dataset_aux = pd.DataFrame()

In [6]:
dataset_aux["R&D Spend"] = dataset["R&D Spend"]
dataset_aux["Administration"] = dataset["Administration"]
dataset_aux["Marketing Spend"] = dataset["Marketing Spend"]



In [7]:
dataset_aux

R&D Spend  Administration  Marketing Spend
0   165349.20       136897.80        471784.10
1   162597.70       151377.59        443898.53
2   153441.51       101145.55        407934.54
3   144372.41       118671.85        383199.62
4   142107.34        91391.77        366168.42
5   131876.90        99814.71        362861.36
6   134615.46       147198.87        127716.82
7   130298.13       145530.06        323876.68
8   120542.52       148718.95        311613.29
9   123334.88       108679.17        304981.62
10  101913.08       110594.11        229160.95
11  100671.96        91790.61        249744.55
12   93863.75       127320.38        249839.44
13   91992.39       135495.07        252664.93
14  119943.24       156547.42        256512.92
15  114523.61       122616.84        261776.23
16   78013.11       121597.55        264346.06
17   94657.16       145077.58        282574.31
18   91749.16       114175.79        294919.57
19   86419.70       153514.11             0.00
20   76253.86       113867.30        298664.47
21   78389.47       153773.43        299737.29
22   73994.56       122782.75        303319.26
23   67532.53       105751.03        304768.73
24   77044.01        99281.34        140574.81
25   64664.71       139553.16        137962.62
26   75328.87       144135.98        134050.07
27   72107.60       127864.55        353183.81
28   66051.52       182645.56        118148.20
29   65605.48       153032.06        107138.38
30   61994.48       115641.28         91131.24
31   61136.38       152701.92         88218.23
32   63408.86       129219.61         46085.25
33   55493.95       103057.49        214634.81
34   46426.07       157693.92        210797.67
35   46014.02        85047.44        205517.64
36   28663.76       127056.21        201126.82
37   44069.95        51283.14        197029.42
38   20229.59        65947.93        185265.10
39   38558.51        82982.09        174999.30
40   28754.33       118546.05        172795.67
41   27892.92        84710.77        164470.71
42   23640.93        96189.63        148001.11
43   15505.73       127382.30         35534.17
44   22177.74       154806.14         28334.72
45    1000.23       124153.04          1903.93
46    1315.46       115816.21        297114.46
47       0.00       135426.92             0.00
48     542.05        51743.15             0.00
49       0.00       116983.80         45173.06

In [8]:
from sklearn.impute import SimpleImputer

In [9]:
Imputer = SimpleImputer(missing_values=0.0, strategy="mean")

In [10]:
Imputer.fit(dataset_aux)

SimpleImputer(missing_values=0.0)

In [11]:
dataset_aux_2 = Imputer.transform(dataset_aux)

In [12]:
dataset_aux_2

array([[165349.2       , 136897.8       , 471784.1       ],
       [162597.7       , 151377.59      , 443898.53      ],
       [153441.51      , 101145.55      , 407934.54      ],
       [144372.41      , 118671.85      , 383199.62      ],
       [142107.34      ,  91391.77      , 366168.42      ],
       [131876.9       ,  99814.71      , 362861.36      ],
       [134615.46      , 147198.87      , 127716.82      ],
       [130298.13      , 145530.06      , 323876.68      ],
       [120542.52      , 148718.95      , 311613.29      ],
       [123334.88      , 108679.17      , 304981.62      ],
       [101913.08      , 110594.11      , 229160.95      ],
       [100671.96      ,  91790.61      , 249744.55      ],
       [ 93863.75      , 127320.38      , 249839.44      ],
       [ 91992.39      , 135495.07      , 252664.93      ],
       [119943.24      , 156547.42      , 256512.92      ],
       [114523.61      , 122616.84      , 261776.23      ],
       [ 78013.11      , 121597.55      

In [13]:
dataset_aux_3 = pd.DataFrame()

In [14]:
dataset_aux_3["R&D Spend"] = dataset_aux_2[:,0]
dataset_aux_3["Administration"] = dataset_aux_2[:,1]
dataset_aux_3["Marketing Spend"] = dataset_aux_2[:,2]
dataset_aux_3["State"] = dataset["State"]

In [15]:
dataset_aux_2

array([[165349.2       , 136897.8       , 471784.1       ],
       [162597.7       , 151377.59      , 443898.53      ],
       [153441.51      , 101145.55      , 407934.54      ],
       [144372.41      , 118671.85      , 383199.62      ],
       [142107.34      ,  91391.77      , 366168.42      ],
       [131876.9       ,  99814.71      , 362861.36      ],
       [134615.46      , 147198.87      , 127716.82      ],
       [130298.13      , 145530.06      , 323876.68      ],
       [120542.52      , 148718.95      , 311613.29      ],
       [123334.88      , 108679.17      , 304981.62      ],
       [101913.08      , 110594.11      , 229160.95      ],
       [100671.96      ,  91790.61      , 249744.55      ],
       [ 93863.75      , 127320.38      , 249839.44      ],
       [ 91992.39      , 135495.07      , 252664.93      ],
       [119943.24      , 156547.42      , 256512.92      ],
       [114523.61      , 122616.84      , 261776.23      ],
       [ 78013.11      , 121597.55      

In [16]:
dataset_aux_3

R&D Spend  Administration  Marketing Spend       State
0   165349.200000       136897.80    471784.100000    New York
1   162597.700000       151377.59    443898.530000  California
2   153441.510000       101145.55    407934.540000     Florida
3   144372.410000       118671.85    383199.620000    New York
4   142107.340000        91391.77    366168.420000     Florida
5   131876.900000        99814.71    362861.360000    New York
6   134615.460000       147198.87    127716.820000  California
7   130298.130000       145530.06    323876.680000     Florida
8   120542.520000       148718.95    311613.290000    New York
9   123334.880000       108679.17    304981.620000  California
10  101913.080000       110594.11    229160.950000     Florida
11  100671.960000        91790.61    249744.550000  California
12   93863.750000       127320.38    249839.440000     Florida
13   91992.390000       135495.07    252664.930000  California
14  119943.240000       156547.42    256512.920000     Florida
15  114523.610000       122616.84    261776.230000    New York
16   78013.110000       121597.55    264346.060000  California
17   94657.160000       145077.58    282574.310000    New York
18   91749.160000       114175.79    294919.570000     Florida
19   86419.700000       153514.11    224494.784894    New York
20   76253.860000       113867.30    298664.470000  California
21   78389.470000       153773.43    299737.290000    New York
22   73994.560000       122782.75    303319.260000     Florida
23   67532.530000       105751.03    304768.730000     Florida
24   77044.010000        99281.34    140574.810000    New York
25   64664.710000       139553.16    137962.620000  California
26   75328.870000       144135.98    134050.070000     Florida
27   72107.600000       127864.55    353183.810000    New York
28   66051.520000       182645.56    118148.200000     Florida
29   65605.480000       153032.06    107138.380000    New York
30   61994.480000       115641.28     91131.240000     Florida
31   61136.380000       152701.92     88218.230000    New York
32   63408.860000       129219.61     46085.250000  California
33   55493.950000       103057.49    214634.810000     Florida
34   46426.070000       157693.92    210797.670000  California
35   46014.020000        85047.44    205517.640000    New York
36   28663.760000       127056.21    201126.820000     Florida
37   44069.950000        51283.14    197029.420000  California
38   20229.590000        65947.93    185265.100000    New York
39   38558.510000        82982.09    174999.300000  California
40   28754.330000       118546.05    172795.670000  California
41   27892.920000        84710.77    164470.710000     Florida
42   23640.930000        96189.63    148001.110000  California
43   15505.730000       127382.30     35534.170000    New York
44   22177.740000       154806.14     28334.720000  California
45    1000.230000       124153.04      1903.930000    New York
46    1315.460000       115816.21    297114.460000     Florida
47   76793.349583       135426.92    224494.784894  California
48     542.050000        51743.15    224494.784894    New York
49   76793.349583       116983.80     45173.060000  California

In [17]:
dataset_aux_4 = pd.get_dummies(dataset_aux_3, drop_first=True)

In [18]:
dataset_aux_4

R&D Spend  Administration  Marketing Spend  State_Florida  \
0   165349.200000       136897.80    471784.100000              0   
1   162597.700000       151377.59    443898.530000              0   
2   153441.510000       101145.55    407934.540000              1   
3   144372.410000       118671.85    383199.620000              0   
4   142107.340000        91391.77    366168.420000              1   
5   131876.900000        99814.71    362861.360000              0   
6   134615.460000       147198.87    127716.820000              0   
7   130298.130000       145530.06    323876.680000              1   
8   120542.520000       148718.95    311613.290000              0   
9   123334.880000       108679.17    304981.620000              0   
10  101913.080000       110594.11    229160.950000              1   
11  100671.960000        91790.61    249744.550000              0   
12   93863.750000       127320.38    249839.440000              1   
13   91992.390000       135495.07    252664.930000              0   
14  119943.240000       156547.42    256512.920000              1   
15  114523.610000       122616.84    261776.230000              0   
16   78013.110000       121597.55    264346.060000              0   
17   94657.160000       145077.58    282574.310000              0   
18   91749.160000       114175.79    294919.570000              1   
19   86419.700000       153514.11    224494.784894              0   
20   76253.860000       113867.30    298664.470000              0   
21   78389.470000       153773.43    299737.290000              0   
22   73994.560000       122782.75    303319.260000              1   
23   67532.530000       105751.03    304768.730000              1   
24   77044.010000        99281.34    140574.810000              0   
25   64664.710000       139553.16    137962.620000              0   
26   75328.870000       144135.98    134050.070000              1   
27   72107.600000       127864.55    353183.810000              0   
28   66051.520000       182645.56    118148.200000              1   
29   65605.480000       153032.06    107138.380000              0   
30   61994.480000       115641.28     91131.240000              1   
31   61136.380000       152701.92     88218.230000              0   
32   63408.860000       129219.61     46085.250000              0   
33   55493.950000       103057.49    214634.810000              1   
34   46426.070000       157693.92    210797.670000              0   
35   46014.020000        85047.44    205517.640000              0   
36   28663.760000       127056.21    201126.820000              1   
37   44069.950000        51283.14    197029.420000              0   
38   20229.590000        65947.93    185265.100000              0   
39   38558.510000        82982.09    174999.300000              0   
40   28754.330000       118546.05    172795.670000              0   
41   27892.920000        84710.77    164470.710000              1   
42   23640.930000        96189.63    148001.110000              0   
43   15505.730000       127382.30     35534.170000              0   
44   22177.740000       154806.14     28334.720000              0   
45    1000.230000       124153.04      1903.930000              0   
46    1315.460000       115816.21    297114.460000              1   
47   76793.349583       135426.92    224494.784894              0   
48     542.050000        51743.15    224494.784894              0   
49   76793.349583       116983.80     45173.060000              0   

    State_New York  
0                1  
1                0  
2                0  
3                1  
4                0  
5                1  
6                0  
7                0  
8                1  
9                0  
10               0  
11               0  
12               0  
13               0  
14               0  
15               1  
16               0  
17               1  
18               0  
19               1  
20               0  
21               1  
22   

In [19]:
from sklearn.preprocessing import MinMaxScaler

In [20]:
minmax = MinMaxScaler()

In [21]:
minmax.fit(dataset_aux_4)

MinMaxScaler()

In [22]:
dataset_5 = minmax.transform(dataset_aux_4)

In [23]:
dataset_5

array([[1.        , 0.65174393, 1.        , 0.        , 1.        ],
       [0.98330473, 0.76197173, 0.94065387, 0.        , 0.        ],
       [0.92774773, 0.37957895, 0.86411523, 1.        , 0.        ],
       [0.87271918, 0.51299839, 0.81147432, 0.        , 1.        ],
       [0.85897541, 0.30532804, 0.77522848, 1.        , 0.        ],
       [0.7969002 , 0.3694479 , 0.76819039, 0.        , 1.        ],
       [0.81351695, 0.73016111, 0.26775527, 0.        , 0.        ],
       [0.7873207 , 0.71745725, 0.68522311, 1.        , 0.        ],
       [0.7281266 , 0.74173276, 0.65912413, 0.        , 1.        ],
       [0.7450698 , 0.43692884, 0.6450106 , 0.        , 0.        ],
       [0.61508879, 0.45150637, 0.48364888, 1.        , 0.        ],
       [0.60755805, 0.30836422, 0.52745495, 0.        , 0.        ],
       [0.56624788, 0.57883556, 0.52765689, 1.        , 0.        ],
       [0.55489304, 0.64106561, 0.53367011, 0.        , 0.        ],
       [0.72449035, 0.8013272 , 0.

In [24]:
y = dataset["Profit"].values

In [25]:
y

array([192261.83, 191792.06, 191050.39, 182901.99, 166187.94, 156991.12,
       156122.51, 155752.6 , 152211.77, 149759.96, 146121.95, 144259.4 ,
       141585.52, 134307.35, 132602.65, 129917.04, 126992.93, 125370.37,
       124266.9 , 122776.86, 118474.03, 111313.02, 110352.25, 108733.99,
       108552.04, 107404.34, 105733.54, 105008.31, 103282.38, 101004.64,
        99937.59,  97483.56,  97427.84,  96778.92,  96712.8 ,  96479.51,
        90708.19,  89949.14,  81229.06,  81005.76,  78239.91,  77798.83,
        71498.49,  69758.98,  65200.33,  64926.08,  49490.75,  42559.73,
        35673.41,  14681.4 ])

In [26]:
from sklearn.model_selection import train_test_split

In [27]:
X_train, X_test, y_train, y_test = train_test_split(dataset_5, y, test_size=0.2, random_state=123)

In [28]:
X_train.shape

(40, 5)

In [29]:
X_test.shape

(10, 5)

In [30]:
from sklearn.linear_model import LinearRegression

In [31]:
rl = LinearRegression()

In [32]:
rl.fit(X_train,y_train)

LinearRegression()

In [33]:
rl.coef_

array([106547.39552059,   4005.40442767,  39372.13902832,   6430.56693802,
         6002.36097206])

In [34]:
rl.intercept_

37004.72706471753

In [35]:
rl.score(X_train,y_train)

0.7683210797989054

In [36]:
rl.score(X_test,y_test)




0.9146894879550872